name:                rawr
version:             0.0.0.1
synopsis:            Anonymous extensible records
description: >
  This library provides anonymous extensible records using GHC 8.0 features, with the following goals/features:

      * The syntax should be very close to that of Haskell's record system.

      * The library should be simple to use and requires no extra boilerplate to setup.

      * There should be minimal runtime overhead and memory footprint.

      * The library does not require @TemplateHaskell@ to use.

      * It should produce good error messages.

      * Minimal dependencies. Currently, it only depends on packages that comes with GHC.

  See @<https://hackage.haskell.org/package/rawr/docs/Data-Rawr.html Data.Rawr>@ for a tutorial of this library.

homepage:            https://github.com/pkmx/rawr
license:             BSD3
author:              PkmX
maintainer:          pkmx.tw@gmail.com
copyright:           2016 PkmX
category:            Records
github:              pkmx/rawr

ghc-options: -Wall

dependencies:
  - base >= 4.11 && < 4.16
  - deepseq >= 1.4 && < 1.5

library:
  ghc-options: -funfolding-use-threshold=20
  source-dirs:     src
  exposed-modules: Data.Rawr
  dependencies:
    - ghc-prim >= 0.5 && < 0.8

tests:
  doctest:
    main: Main.hs
    source-dirs:
      - tests/doctest
    dependencies:
      - doctest >= 0.11 && < 0.19
      - lens >= 4.14 && < 5.1
#  datasize:
#    main: Main.hs
#    source-dirs:
#      - tests/datasize
#    dependencies:
#      - rawr
#      - ghc-datasize == 0.2.*
#      - tasty == 0.11.*
#      - tasty-hunit == 0.9.*

benchmarks:
  perf:
    main: Main.hs
    source-dirs:
      - benchmarks/perf
    dependencies:
      - rawr
      - criterion >= 1.1 && < 1.6
    ghc-options: -funfolding-use-threshold=20

extra-source-files:
  - README.md
