name:                rawr
version:             0.0.0.1
synopsis:            Anonymous extensible records
description: >
  This library provides anonymous extensible records using GHC 8.0 features, with the following goals/features:

      * The syntax should be very close to that of Haskell's record system.

      * The library should be simple to use and requires no extra boilerplate to setup.

      * There should be minimal runtime overhead and memory footprint.

      * The library does not require @TemplateHaskell@ to use.

      * It should produce good error messages.

      * Minimal dependencies. Currently, it only depends on packages that comes with GHC.

  See @<https://hackage.haskell.org/package/rawr/docs/Data-Rawr.html Data.Rawr>@ for a tutorial of this library.

homepage:            https://github.com/pkmx/rawr
license:             BSD3
author:              PkmX
maintainer:          pkmx.tw@gmail.com
copyright:           2016 PkmX
category:            Records

ghc-options: -Wall

dependencies:
  - base == 4.9.*
  - deepseq == 1.4.*

library:
  ghc-options: -funfolding-use-threshold=20
  source-dirs:     src
  exposed-modules: Data.Rawr
  dependencies:
    - ghc-prim == 0.5.*
    - template-haskell == 2.11.*

tests:
  doctest:
    main: Main.hs
    source-dirs:
      - tests/doctest
    dependencies:
      - doctest == 0.11.*
      - lens == 4.14.*
  datasize:
    main: Main.hs
    source-dirs:
      - tests/datasize
    dependencies:
      - rawr
      - ghc-datasize == 0.1.*
      - tasty == 0.11.*
      - tasty-hunit == 0.9.*

benchmarks:
  perf:
    main: Main.hs
    source-dirs:
      - benchmarks/perf
    dependencies:
      - rawr
      - criterion == 1.1.*
    ghc-options: -funfolding-use-threshold=20

extra-source-files:
  - README.md
