name:                rawr
version:             0.0.0.0
synopsis:            Anonymous extensible records and variant types
description:         See "Data.Rawr" for a tutorial of this library.
homepage:            https://github.com/pkmx/rawr
license:             BSD3
author:              PkmX
maintainer:          pkmx.tw@gmail.com
copyright:           2016 PkmX
category:            Records

ghc-options: -Wall

dependencies:
  - base == 4.9.*
  - deepseq == 1.4.*

library:
  ghc-options: -funfolding-use-threshold=20
  source-dirs:     src
  exposed-modules: Data.Rawr
  dependencies:
    - ghc-prim == 0.5.*
    - template-haskell == 2.11.*

tests:
  doctest:
    main: Main.hs
    source-dirs:
      - tests/doctest
    dependencies:
      - doctest == 0.11.*
      - lens == 4.14.*
  datasize:
    main: Main.hs
    source-dirs:
      - tests/datasize
    dependencies:
      - rawr
      - ghc-datasize == 0.1.*
      - tasty == 0.11.*
      - tasty-hunit == 0.9.*

benchmarks:
  perf:
    main: Main.hs
    source-dirs:
      - benchmarks/perf
    dependencies:
      - rawr
      - criterion == 1.1.*
    ghc-options: -funfolding-use-threshold=20
